apiVersion: v1
kind: Service
metadata:
  name: mediamtx
  namespace: sitaware
spec:
  selector:
    app: mediamtx
  ports:
    - name: webrtc
      port: 8889
      targetPort: 8889
    - name: rtsp
      port: 8554
      targetPort: 8554
    - name: api
      port: 9997
      targetPort: 9997
