apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "sitaware.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_USERNAME: {{ .Values.secrets.adminUsername | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
  ADMIN_EMAIL: {{ .Values.secrets.adminEmail | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  DB_USER: {{ .Values.secrets.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  S3_ACCESS_KEY: {{ .Values.secrets.s3AccessKey | quote }}
  S3_SECRET_KEY: {{ .Values.secrets.s3SecretKey | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.secrets.corsAllowedOrigins | quote }}
