#!/bin/sh
# ci_post_clone.sh — Xcode Cloud runs this after `git clone`, before resolving
# dependencies. Keep it idempotent and fast.
#
# Responsibilities:
#   1. Write a minimal Local.xcconfig so the build doesn't fail on the missing
#      (gitignored) developer-specific signing file. Xcode Cloud handles signing
#      via its App Store Connect integration, so we MUST NOT set DEVELOPMENT_TEAM
#      or CODE_SIGN_STYLE here.
#   2. Derive a monotonic CFBundleVersion from the git commit count so every
#      TestFlight upload has a unique, ever-increasing build number. Exported
#      via CI_XCODE_CLOUD_BUILD_NUMBER so the xcconfig picks it up.
#   3. (Optional) Regenerate the Xcode project from project.yml via XcodeGen.
#      Enabled only if REGENERATE_XCODEGEN=1 is set in the workflow's env; by
#      default we trust the committed pbxproj.

set -euo pipefail

# Xcode Cloud exposes the repo root via $CI_PRIMARY_REPOSITORY_PATH.
cd "$CI_PRIMARY_REPOSITORY_PATH/clients/ios"

# ---- 1. Local.xcconfig --------------------------------------------------------
cat > Local.xcconfig <<'EOF'
// Generated by ci_post_clone.sh for Xcode Cloud builds.
// Signing is managed by Xcode Cloud's App Store Connect integration —
// do not set DEVELOPMENT_TEAM or CODE_SIGN_STYLE here.
CODE_SIGN_ENTITLEMENTS = Vincenty/Resources/Vincenty.entitlements

// Build number injected from git commit count (see ci_post_clone.sh).
CURRENT_PROJECT_VERSION = ${CI_BUILD_NUMBER}
EOF

# ---- 2. Build number from git -------------------------------------------------
BUILD_NUMBER=$(git -C "$CI_PRIMARY_REPOSITORY_PATH" rev-list --count HEAD)
echo "CI_BUILD_NUMBER=$BUILD_NUMBER" >> "${CI_XCODE_CLOUD_ENV_FILE:-/dev/null}" 2>/dev/null || true
# xcconfig reads from the process env via the ${} syntax above; export it too.
export CI_BUILD_NUMBER="$BUILD_NUMBER"
# Rewrite the placeholder we just templated so it reflects the resolved value.
/usr/bin/sed -i '' "s|\${CI_BUILD_NUMBER}|$BUILD_NUMBER|g" Local.xcconfig

echo "ci_post_clone: wrote Local.xcconfig with build number $BUILD_NUMBER"

# ---- 3. Optional: regenerate Xcode project ------------------------------------
if [ "${REGENERATE_XCODEGEN:-0}" = "1" ]; then
  if ! command -v xcodegen >/dev/null 2>&1; then
    echo "Installing XcodeGen…"
    brew install xcodegen
  fi
  xcodegen generate
  echo "ci_post_clone: regenerated Vincenty.xcodeproj from project.yml"
fi

# ---- 4. Pre-resolve Swift packages (retry on transient DNS/network) ----------
# MapLibre is a binary SPM target hosted on github.com/releases. Xcode Cloud
# occasionally sees transient DNS failures fetching it; retry a few times so a
# flaky network doesn't fail the whole build.
for attempt in 1 2 3; do
  if xcodebuild -resolvePackageDependencies \
       -project Vincenty.xcodeproj \
       -scheme Vincenty \
       -clonedSourcePackagesDirPath "$CI_DERIVED_DATA_PATH/SourcePackages"; then
    echo "ci_post_clone: package dependencies resolved (attempt $attempt)"
    break
  fi
  echo "ci_post_clone: package resolve failed (attempt $attempt); retrying…"
  sleep $((attempt * 5))
  [ "$attempt" = "3" ] && { echo "ci_post_clone: giving up after 3 attempts"; exit 1; }
done
